### ISSUE TITLE
DOCKER_BUILDKIT not working

### ISSUE THREAD

**Issue by masip85** [docker-snap/docker-snap#1]
I understand this docker version has BUILDKIT. To be enabled, in no snapped docker there are two options:
`$ DOCKER_BUILDKIT=1 docker build .`

But, trying docker docs simple example (which works fine with not snapped docker), with docker snap I obtain **parse** errors. (Doesn't recognize any buildkit characteristic in RUN statements). So, I wanted to use the second option to use this characteristic:

```
To enable docker BuildKit by default, set daemon configuration in /etc/docker/daemon.json feature to true and restart the daemon:

{ "features": { "buildkit": true } }
```

This config file is the repo, but once is installed I can't modify it. 

Any workaround?

**Comment by anonymouse64** [comment]
> This config file is the repo, but once is installed I can't modify it.

The config file should be in `/var/snap/docker/current/config/daemon.json` and should be writable for you to edit it, does that not work for some reason?

**Comment by masip85** [comment]
What the difference between:
/var/snap/docker/current/config/daemon.json and /snap/docker/current/config/daemon.json
Anyway:
root@bionic:/var/snap/docker# ls -lah /var/snap/docker/current/config/daemon.json
-rw-r--r-- 1 root root 72 Aug 20 11:57 /var/snap/docker/current/config/daemon.json

![imagen](https://user-images.githubusercontent.com/12863854/94033518-541e2a80-fdc1-11ea-901b-5bb42b185053.png)

BUT!!!
`root@bionic:/var/snap/docker# nano /var/snap/docker/current/config/daemon.json`
![imagen](https://user-images.githubusercontent.com/12863854/94033571-65673700-fdc1-11ea-80f9-0646e69cf092.png)

**Comment by anonymouse64** [comment]
/var/snap is writable (it's called $SNAP_DATA) and /snap (called $SNAP) is not writable (it comes from the read-only squashfs that is the snap format). The file from $SNAP is there so we can initialize the writable config in $SNAP_DATA with what's in $SNAP for new installs.

**Comment by masip85** [comment]
I didn't paste correctly the second picture. What I obtain from ` root@bionic:/var/snap/docker# nano /var/snap/docker/current/config/daemon.json` is that it is not writable.

**Comment by anonymouse64** [comment]
It should be writable, from the output of your screenshot it is writable by root. What error message is returned or what happens if you try to edit it as root?

**Comment by masip85** [comment]
As root I execute a nano:

![image](https://user-images.githubusercontent.com/12863854/94141606-4920d400-fe6d-11ea-99f8-2208e354526f.png)

**Comment by anonymouse64** [comment]
Is `nano` a snap on this machine? what is `which nano`?

**Comment by anonymouse64** [comment]
Also I guess while we are gathering debugging info what is `snap version` on your machine?

**Comment by masip85** [comment]
Yes,is a snap nano.Remote vscode can't neither. But I guess both doesn't work because it an Ubuntu Core (18). Otherwise, vi can write,  but I don't manage to do it from there correctly because it has arrows strange issue and I cannot move to the position where I want to write. But I guess that is another issue.

root@bionic:/home/vmasip# snap version
snap    2.46.1
snapd   2.46.1
series  16
kernel  5.3.0-1033-raspi2

**Comment by tianon** [comment]
Something like the following might work:

```console
$ cp /var/snap/docker/current/config/daemon.json ~/
$ nano ~/daemon.json
$ mv ~/daemon.json /var/snap/docker/current/config/daemon.json
```

**Comment by tianon** [comment]
(then `snap restart docker.dockerd`)

**Comment by masip85** [comment]
I managed with that how to edit it, and then:
`sudo snap disable docker`
`sudo snap enable docker`

It work,but now,when is activated a new issue appears:

```
vmasip@bionic:~/git-arm64/tmp$ sudo docker build --no-cache  . 
[+] Building 1.5s (6/6) FINISHED                                                                                
 => [internal] load build definition from Dockerfile                                                       0.0s
 => => transferring dockerfile: 37B                                                                        0.0s
 => [internal] load .dockerignore                                                                          0.1s
 => => transferring context: 2B                                                                            0.0s
 => [internal] load metadata for docker.io/arm64v8/alpine:3.7                                              0.0s
 => CACHED [1/3] FROM docker.io/arm64v8/alpine:3.7                                                         0.0s
 => [2/3] RUN whoami                                                                                       0.6s
 => ERROR [3/3] RUN apk add git                                                                            0.8s
------                                                                                                          
 > [3/3] RUN apk add git:
#6 0.726 ERROR: Unable to lock database: Permission denied
#6 0.727 ERROR: Failed to open apk database: Permission denied
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apk add git]: runc did not terminate sucessfully
```
It dissapears when buildkit is disabled

**Comment by tianon** [comment]
Unfortunately, that sounds to me like you're hitting what we also discovered/hit trying to write a test for this in https://github.com/docker-snap/docker-snap/pull/6#issuecomment-700243967.

**Comment by masip85** [comment]
> Unfortunately, that sounds to me like you're hitting what we also discovered/hit trying to write a test for this in [#6 (comment)](https://github.com/docker-snap/docker-snap/pull/6#issuecomment-700243967).

Mmmmm, anyworkaround?
