### ISSUE TITLE
Docker snap doesn't work on ZFS

### ISSUE THREAD

**Issue by omar-selo** [docker-snap/docker-snap#112]
I'm facing the same issue mentioned [here](https://forum.snapcraft.io/t/docker-snap-failed-to-mount-overlay-and-where-to-report-bugs/20010). Basically, on a ZFS system docker snap just doesn't work. The workaround is to modify the storage driver specified in `/var/snap/docker/current/config/daemon.json` to zfs. Ideally, this configuration should be part of snap's installation. If not at least it would be nice to have this info in the readme.

**Comment by zhsj** [comment]
IMO, we could stop setting storage-driver in daemon.json, then docker will determinate the best one itself.

Not sure if there's any side-effect.

**Comment by xnox** [comment]
> 

at install time sure, but will it be preserved on snap refreshes? I believe we want to continue to use storage-driver A on existing installs, even if storage-driver B has become the new best default.

**Comment by tianon** [comment]
IMO removing the setting is probably the best answer -- Docker itself will automatically choose the "best" one, preferring what already exists followed by https://github.com/moby/moby/blob/cba6f2d42698b1d15e031efa18a59843859f2200/daemon/graphdriver/driver_linux.go#L53

**Comment by xnox** [comment]
let's do this then.
