### ISSUE TITLE
Docker-compose not working well while installing from snap

### ISSUE THREAD

**Issue by Taytay884** [docker-snap/docker-snap#12]
Hi, while installing docker using snap the `config.json` placed in `~/snap/docker/471/.docker`.
When using docker-compose to fetch an image it's looking for `~/.docker` which is empty and then you see this error `unauthorized: authentication required`

I have fixed it by moving the config.json to ~/.docker

Another error I got:
`\"mountpoint for devices not found\"`
And now I removed the snap version and installed the normal one and everything works great.

**Comment by anonymouse64** [comment]
> Another error I got:
> `\"mountpoint for devices not found\"`

Could you explain what you did to cause this and provide any logs you might have when you tried this?
```
snap version
snap list docker
journalctl --no-pager -u snap.docker.dockerd
```

**Comment by Fuseteam** [comment]
docker-compose works fine on my end

**Comment by Taytay884** [comment]
Sorry for my inactivity, I didn't use it for long time ago.
