### ISSUE TITLE
draft release notes - v20.10.23

### ISSUE THREAD

**Issue by xnox** [docker-snap/docker-snap#120]
Older v20.10.17 docker snap is now published in core18/stable channel. It will remain unchanged, and unlikely to receive any future maintainance.

v20.10.23 docker-snap changes
* docker versions updated to v20.10.23
* snap base upgraded from core18 to core22
* assumes snapd 2.59.1 currently in beta channel
* nftables used by default
* compose v2 is now the default and only compose implementation
* deprecated compose v1 removed
* deprecated machine command plugin removed

**Comment by tianon** [comment]
https://github.com/docker-snap/docker-snap/pull/99 too, or was that already published on the older channel?

**Comment by xnox** [comment]
promoted to beta

**Comment by xnox** [comment]
https://github.com/docker-snap/docker-snap/releases/tag/v20.10.23 generated & discussion forum opened at https://github.com/docker-snap/docker-snap/discussions/123

will also post about this in snapcraft forum.
