### ISSUE TITLE
Improve nvidia integration on classic systems

### ISSUE THREAD

**Issue by xnox** [docker-snap/docker-snap#127]
Improve checks to see if we can detect nvidia hw presence with lspci.

Improve library usage to see if we can use hostfs libraries on classic systems.

Improve detection and wait on nvidia-assemble.

**Comment by jocado** [comment]
Just FYI @xnox - some of this was done with https://github.com/docker-snap/docker-snap/pull/128

At least:
- Improve checks to see if we can detect nvidia hw presence with lspci

**Comment by jocado** [comment]
@xnox Can I ask if any of the remaining work here is a blocker for release to current/stable or not ?

Thanks.

**Comment by xnox** [comment]
nothing here is a blocker for releases.

separately there was progressive release to .24/core22 based docker snap to latest/stable, which is now almost complete. I will start another round of promotion shortly.

which specific changes are you after in latest/stable?

**Comment by jocado** [comment]
> nothing here is a blocker for releases.

:+1: 

> which specific changes are you after in latest/stable?

Ideally, everything as of my most recent PR, which I think was revision `2868`.  As it contained a bug fix too for some install scenarios with NVIDIA support, I would suggest that us the best current candidate for stable release target including NVIDIA support.

**Comment by jocado** [comment]
I believe I have a working solution for classic, testing in this branch: https://github.com/jocado/docker-snap/tree/cdi-with-classic

But, there is a small change in the snapd opengl interface required.  I've created a PR: https://github.com/snapcore/snapd/pull/13847

Once I have some feedback on that I will create a PR here for the snap changes.
