### ISSUE TITLE
Cannot use plugins (e.g., compose v2) from a snap that connects via snap interface

### ISSUE THREAD

**Issue by anthonybacio** [docker-snap/docker-snap#137]
When revision 2883 was promoted to the latest/stable channel, the docker compose v2 command became inaccessible to our snap package, which interfaces using the docker and docker-executables slots.

```
root@ubuntu22g7:/tmp# snap run --shell codelogic.pre-start-codelogic

root@ubuntu22g7:/tmp# docker-compose version
bash: docker-compose: command not found

root@ubuntu22g7:/tmp# docker compose version
docker: 'compose' is not a docker command.
See 'docker --help'
```

The `/usr/libexec/docker/cli-plugins/` directory is available in our snap:

```
root@ubuntu22g7:/snap/codelogic/x1/docker-snap# ls -lisah ./usr/libexec/docker/cli-plugins/
total 100M
976   0 drwxr-xr-x 2 root root  58 Apr 10 02:58 .
975   0 drwxr-xr-x 3 root root  34 Apr 10 02:53 ..
977 48M -rwxr-xr-x 1 root root 48M Apr 10 02:53 docker-buildx
978 53M -rwxr-xr-x 1 root root 53M Apr 10 02:53 docker-compose
```

We can run `docker-compose` directly. _However, we need the CLI options which are now handled by docker._

We cannot use the docker snap package in `core18/stable` because:

1. This would force our customers to use a version that is no longer receiving security updates;
2. Customers would have to manually install that version because `plugs.default-provider` does not accept channels in the same manner as `parts.<part-name>.build-snaps`.

Our snap package connects via the docker and docker-executables slots:
```
root@ubuntu22g7:/tmp# snap connections codelogic
Interface                    Plug                          Slot                       Notes
content[docker-executables]  codelogic:docker-executables  docker:docker-executables  manual
docker                       codelogic:docker              docker:docker-daemon       manual
network                      codelogic:network             :network                   -
```

**Comment by xnox** [comment]
@anthonybacio this has been identified by @dilyn-corner earlier as well. As originally designed and implemented docker-executables interface never correctly provided access to docker plugins i.e. (`docker compose`, `docker machine` as used to be shipped and so on). The correct way to use docker-executables, requires one to have a layout options set in your own snap. Please see example fixups shown here https://github.com/canonical/iot-field-example-snaps/commit/cf7859a0fd0f27ca8778562de9c5c301f7ea06bb it is an oversight from the original implementation of the docker-executables interface. But with those layout fixes, `docker compose` just works via docker-executables interface with the latest/stable version of docker. let me know if this is sufficient for you, and also note these layout fixes are backwards compatible with older revisions of docker and core18/stable channel.

**Comment by anthonybacio** [comment]
@xnox **Thank you Dimitri!** That is more than sufficient. We really appreciate the help! Also, thank you for replying so quickly, I replaced my workaround with Dilyn's superior method.

@dilyn-corner Thank you for writing such a clear and helpful example. It's better than the ones I used months ago for the original implementation.
