### ISSUE TITLE
Connecting to docker-executables fails with 'connection not allowed by slot rule of interface "content"'

### ISSUE THREAD

**Issue by anthonybacio** [docker-snap/docker-snap#145]
I'm tempted to make this a forum post but since we encounter the exact same thing with that useful [using-docker/snap/snapcraft.yaml](https://github.com/canonical/iot-field-example-snaps/blob/main/using-docker/snap/snapcraft.yaml) example, I'm posting it here.

When installed in strict confinement, connecting to docker results in 
```
root@ubuntu22g7:/# sudo snap connect codelogic:docker-executables docker:docker-executables
error: cannot perform the following tasks:
- Connect codelogic:docker-executables to docker:docker-executables (connection not allowed by slot rule of interface "content")
```

This doesn't happen when installed with `--dangerous`.

This also happens with that useful [using-docker/snap/snapcraft.yaml](https://github.com/canonical/iot-field-example-snaps/blob/main/using-docker/snap/snapcraft.yaml) example. Thanks again to @dilyn-corner, without that example, we wouldn't have known that snapd 2.59.1 is required (and to @xnox for pointing us to it).

In case you're wondering: yes, to reproduce our tester's environment I changed the name of the `using-docker` snap (that was the only change), built it using snapcraft 7, uploaded it to our store, then installed it on another system using `snap install`. I even used the `--purge` option when removing the previous snap.

Except for the name of the directory (we use `target: $SNAP/docker-snap` instead of `$SNAP/docker-bin`) our docker plug is identical to the one in the example.

Details:
- Build using snapcraft 5, snapcraft 7 (our snap uses 5, the sample requires version 7).
- Docker is 20.10.24  2893  latest/stable
- Snapd is snapd  2.59.4   19361  latest/stable

The plug and relevant information for the using-docker sample:
```
…
name: tocker
base: core22
…
confinement: strict

# Due to recent changes in the Docker snap, snapd 2.59.1 is required.
# If an older version of snapd is needed, please use Docker on 18/stable.
assumes: [snapd2.59.1]
…
plugs:
  # NOTE: the docker-executables interface may one day be deprecated
  docker-executables:
    interface: content
    content: executables
    target: $SNAP/docker-bin
    default-provider: docker
```

Our plug and relevant configuration:
```
…
base: core22
…
confinement: strict
…
# If snap features fail and there have been no changes, check the example
# at https://github.com/canonical/iot-field-example-snaps
assumes:
  - snapd2.59.1

plugs:
  # NOTE: the docker-executables interface may one day be deprecated, see 
  # https://github.com/canonical/iot-field-example-snaps/blob/main/using-docker/snap/snapcraft.yaml
  docker-executables:
    description: |
      Adds the docker command to the codelogic snap directory tree $SNAP/docker-snap
    interface: content
    content: executables
    target: $SNAP/docker-snap
    default-provider: docker
```

**Comment by dilyn-corner** [comment]
That's an interesting problem.

Note that neither I nor my automation for that repository experience this problem; did a local build just now to confirm and the build and testing succeeded on Monday when the automation ran.

You can check if some more useful information is supplied in snapd's changelog; run `snap changes` to see a list of recent changes, and `snap change $ID` to check for more details on a particular change ID.
It might not be useful but you can also set `SNAPD_DEBUG=1` and `SNAPD_DEBUG_HTTP=7` to try and squeeze more information out of `snapd`, but I don't often use those variables so I'm not certain if they expose much of import here.

**Comment by anthonybacio** [comment]
Thank you @dilyn-corner 

This is becoming more interesting since apparently we're the only ones experiencing it. (Well, us and our QA team.)

To be on the safe side, I again rolled back to a clean VM and updated/installed.

Thank you for reminding me: I neglected to include the output of `snap changes ID`. Unfortunately, it only provides consistency:

```
root@ubuntu22g7:~$ snap change 17
2023/06/13 10:22:35.774809 tool_linux.go:204: DEBUG: restarting into "/snap/snapd/current/usr/bin/snap"
Status  Spawn               Ready               Summary
Error   today at 10:19 PDT  today at 10:19 PDT  Connect codelogic:docker-executables to docker:docker-executables

......................................................................
Connect codelogic:docker-executables to docker:docker-executables

2023-06-13T10:19:16-07:00 ERROR connection not allowed by slot rule of interface "content"
```

I hadn't thought to check the metadata, thanks for that too!

Unfortunately, the slot looks just fine:
```
slots:
  docker-daemon:
    interface: docker
  docker-executables:
    content: docker-executables
    interface: content
    read:
    - .
```

Just to be on the safe side, I took a look at the metadata for the app also. It looks fine:
```
plugs:
  docker-executables:
    content: executables
    interface: content
    target: $SNAP/docker-bin
    default-provider: docker
```

I suppose that's not surprising, if I install without uploading to the snap store, it works fine.

Thanks for mentioning `SNAPD_DEBUG` - I'm sure it's documented somewhere but it's not mentioned on the [Debugging snaps](https://snapcraft.io/docs/debug-snaps) page so if I ran across it, I forgot about it.

That does remind me that `journalctl` reports the error:
```
Jun 13 10:33:39 ubuntu22g7 snapd[2065]: taskrunner.go:289: [change 18 "Connect codelogic:docker-executables to docker:docker-executables" task] failed: connection not allowed by slot rule of interface "content"
```

Not surprisingly, `snappy-debug` does not report anything.

Your example is the best docker example of how to use docker. If you can think of any other avenue, I'm game to try it!

**Comment by dilyn-corner** [comment]
I appreciate the kind words :)

A "works for me" bug is the worst sort of bug to triage... 🤔 

Just to be clear:
What is the base of the snap you're adding this plug to? The target of my doc is `core2{0,2}` and I'm uncertain if there's a behavioral change between bases with content interfaces that might illuminate this problem. Does the interface connect fine if you exactly clone the example repository and build the `using-docker/` snap with Snapcraft 7.x?

**Comment by anthonybacio** [comment]
They are well deserved!

Yes! Frustrating for everyone, so I do appreciate your help!

I did check for this error and there _was_ a snap bug but that was fixed a couple of years ago.

We are also using core22.

Yes, I cloned (well, actually, I downloaded the zip file), installed snapcraft 7, and built the snap. The only changes are the name and version:

```
name: codelogic
base: core22
version: '99.9'
```

When installed using `snap install --dangerous` or even `—dangerous —jailmode` it connects fine.

```
root@ubuntu22g7:/tmp# snap install --dangerous /tmp/tocker_1.0_amd64.snap 
tocker 1.0 installed
root@ubuntu22g7:/tmp# sudo snap connect tocker:docker-executables docker:docker-executables
root@ubuntu22g7:/tmp# 
```

Or, after changing `tocker` to `codelogic` and changing the version number (just so our QA team won't use it):

```
root@ubuntu22g7:/tmp# snap install --dangerous /tmp/codelogic_99.9_amd64.snap 
codelogic 99.9 installed
root@ubuntu22g7:/tmp# sudo snap connect codelogic:docker-executables docker:docker-executables
root@ubuntu22g7:/tmp# 

```

The snaps are identical, expect for being packaged with a different name and version:
```
root@ubuntu22g7:/tmp# ls -ltr /tmp/*.snap
-rw-r--r-- 1 abacio abacio 872448 Jun 13 11:12 /tmp/tocker_1.0_amd64.snap
-rw-r--r-- 1 abacio abacio 872448 Jun 13 11:15 /tmp/codelogic_99.9_amd64.snap
```

But, in short, yep, no changes to the example.

**Comment by dilyn-corner** [comment]
I uploaded a build of my example snap to a store and I was able to reproduce your bug! Very interesting indeed.

Asked someone to sanity check me and it was pointed out to me that

```
    content: executables
```

Should instead be 

```
    content: docker-executables
```

The `content` identifier has to be the same on both the slot and plug side to disambiguate which content interface one might mean if a snap happened to provide multiple content interfaces.

I made the change, built the snap, pushed it to a store, installed it and of course, works without a hitch now.

I think it's a bug that this error doesn't happen when installing a locally built snap. I imagine we wouldn't have this error if we downloaded a snap from the store, didn't acknowledge the accompanying assertion, and instead used `--dangerous` to install the snap.


I'll update my example, let me know if this issue persists!

**Comment by anthonybacio** [comment]
https://media.giphy.com/media/RipfZWzjUDH25euMpM/giphy-downsized.gif

**That was it!** Like many things, it seems clear in hindsight.

Thank you very much @dilyn-corner!

This behavior is inconsistent. I'm happy to open an issue against… `snapd`?

For now, I'll close _this_ issue and, again, please accept my thanks.
