### ISSUE TITLE
Promote current edge to stable ?

### ISSUE THREAD

**Issue by jocado** [docker-snap/docker-snap#147]
Hi @xnox 

Is it ok to promote the current `latest/edge` channel to `latest/stable` ?

It will include the changes merged here, which is mainly why I'm asking:
- https://github.com/docker-snap/docker-snap/pull/144

Thanks!

**Comment by xnox** [comment]
urgh, yes......

**Comment by jocado** [comment]
> urgh

If t's painful @xnox , I'd be to help out with snap maintenance, but I would need the appropriate access etc.

**Comment by jocado** [comment]
Hi @xnox 

I understand you are probably very busy.  Can you please give an approximate ETA on this so I can plan around it ?

Also, I repeat my offer to somehow help out with snap maintenance, if it's feasible.

Thanks.
