### ISSUE TITLE
ubuntu22.04 nvidia can't start

### ISSUE THREAD

**Issue by fengjk12138** [docker-snap/docker-snap#148]
OS: `ubuntu22.04.2` server version

I have install nvidia driver. In my host, `nvida-smi` is normal.

install cmd: 
```shell
snap install docker
docker pull nvidia/cuda:11.7.1-runtime-ubuntu22.04
docker run -it --gpus all d916bd2c64a8
```
The errors are below
```shell
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
ERRO[0000] error waiting for container: context canceled 
```

And I can run hello-world docker.

**Comment by jocado** [comment]
Hi @fengjk12138 

The nvidia support in the snap is currently only developed for Ubuntu Core, and not Ubuntu Classic [ such as standard desktop and server etc ].
- https://github.com/docker-snap/docker-snap#nvidia-support-on-ubuntu-core-22

I would like to take a look at adding support on classic, but have not got round to it yet.

If you familiar with snap development, and are willing, perhaps you can try submitting a PR ?


Cheers,
Just
