### ISSUE TITLE
Upgrade to base: core20

### ISSUE THREAD

**Issue by tianon** [docker-snap/docker-snap#15]
(copying salient points from https://github.com/docker-snap/docker-snap/issues/8 to a dedicated issue)

> There also would be the potentially significant amount of snapcraft'ing involved in porting the snapcraft.yaml to use `base: core20` instead of our current implicit `core` base.

> Yeah, porting the Snap to `base: core20` has been on my TODO list for a while to at least consider and look into deeper, but setting up a development environment for building `base: core20` snaps is _way_ more complicated than `base: core`, so it's something that's hard for me to be motivated to spend a lot of time on.

> Porting to core20 also brings with it the complicated question of supporting i386 - do we drop it or do we maintain an i386 only version of the snap based on core16/core18? See https://forum.snapcraft.io/t/how-to-best-handle-i386-when-moving-a-snap-to-base-core20/17680 for more discussion

**Comment by tianon** [comment]
Copying from https://github.com/docker-snap/docker-snap/pull/11#issuecomment-772011925 (because it's more relevant here):

> I'm not running snap, lxd, or multipass locally (and none of them work super great inside a Docker container), and my dev environment is a VM that doesn't do nested VMs, so the workflow changes required for that are kind of a large hurdle for me (and the biggest reason that's not resolved beyond the issues listed in #15 like what to do about i386).

**Comment by anonymouse64** [comment]
Well as a stepping stone you could do `base: core18`, that at least solves the i386 question since core18 snaps still use i386

**Comment by galgalesh** [comment]
In case it helps; if you're using `base: core18`, you can direct snapcraft to use an LXD container instead of a VM by using `snapcraft --use-lxd`. This is useful in VM's.

More info: https://snapcraft.io/docs/build-on-lxd

**Comment by tianon** [comment]
Thanks for the tips (and the push)! 🥳

**Comment by DonCamillo72** [comment]
Hi, is porting the snap to "base: core20" still on the agenda? 
It doesn't seem trivial according to the statements in this issue and issue https://github.com/docker-snap/docker-snap/issues/8.
What are the challenges and side effects on porting to "base: core20"?

**Comment by tianon** [comment]
I think figuring out what to do about i386 is the current blocker for porting to `core20` -- we closed this issue by updating to `core18`, and in doing so had to overcome most of the other obstacles. :+1:
