### ISSUE TITLE
Docker is not working in 20.10.24 snap version

### ISSUE THREAD

**Issue by tobiasz-gleba** [docker-snap/docker-snap#156]
Plz update the docker version ASAP, because in the `20.10.24` one there is an [error](https://stackoverflow.com/questions/77225539/docker-compose-error-internal-booting-buildkit-http-invalid-host-header) that crashes the builds.

**Comment by TM-Baier** [comment]
I just run into the same issue. Can not build with version 20.10.24 (2904). I only get
```
docker compose build
[+] Building 0.0s (0/0)
http: invalid Host header
```

**Comment by ry8806** [comment]
Here is a link to the issue on the [Docker/Moby GitHub Repo](https://github.com/moby/moby/issues/45935).

Looks to have been fixed around mid-July

**Comment by emil10001** [comment]
I am seeing the same issue with `http: invalid Host header` whenever I issue `docker compose build`. 

Installing `edge` unblocked me, although I would prefer to be on `stable`. 

For others who might be stuck and want to switch to get unblocked, here's the StackOverflow solution that's linked above: `sudo snap refresh docker --channel=latest/edge`

**Comment by lucaskanashiro** [comment]
Version `24.0.5` is available in the `latest/stable` for a while.
