### ISSUE TITLE
where to locate the docker.sock 

### ISSUE THREAD

**Issue by oacevedo** [docker-snap/docker-snap#20]
I'm using traefik and I need to map the /var/run/docker.sock. I can't find it inside the /var/snap folder either

**Comment by anonymouse64** [comment]
The docker socket should be in the regular location, even if you are using the docker snap. Are you sure that the docker snap is enabled? What is the output of the following commands:
```
snap version
snap list docker
snap services docker
```

**Comment by oacevedo** [comment]
- snap version 
`snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.04
kernel  5.4.0-60-generic`

- snap list docker
`Name    Version   Rev  Tracking       Publisher   Notes
docker  19.03.11  471  latest/stable  canonical✓  -`

- snap services docker
`Service         Startup  Current  Notes
docker.dockerd  enabled  active   -`
