### ISSUE TITLE
Update the docker snap in the snap store

### ISSUE THREAD

**Issue by mattixtech** [docker-snap/docker-snap#21]
Hello,

We are currently using the docker snap and are encountering the bug fixed in the following PR: https://github.com/docker-snap/docker-snap/pull/9

Could we get a new release including this fix pushed to the snap store so we can start using the fixed version of the docker snap?

Let me know if there is anything I can do to help or speed this along :)

Thanks

**Comment by tianon** [comment]
The latest build (and automatic builds on merges to this repo, in fact) is available in the edge channel (`snap install --edge docker`) -- there's some extra steps/verification that happen for it to be promoted to the stable channel and those are happening behind the scenes but have hit some snags that are being worked through (honestly not sure what it's going to take to overcome them). :sweat_smile:

**Comment by mattixtech** [comment]
> The latest build (and automatic builds on merges to this repo, in fact) is available in the edge channel (`snap install --edge docker`) -- there's some extra steps/verification that happen for it to be promoted to the stable channel and those are happening behind the scenes but have hit some snags that are being worked through (honestly not sure what it's going to take to overcome them). 😅

Thanks for pointing out the edge channel being auto updated. For our purposes we are trying to use this in an IoT appliance in prod production in the near future and we likely wouldn't want to be dependent on the edge channel for that. Perhaps in the meantime we will play around with the version on edge and wait to see if the release version can be updated. If there is anything we can do to help push that along let me know.

Thanks

**Comment by tianon** [comment]
This is fixed! :smile:
