### ISSUE TITLE
Failure loading image from .tar.xz

### ISSUE THREAD

**Issue by OctanMan** [docker-snap/docker-snap#30]
Attempting to load a docker image created with `docker save` and compressed with `xz` results in the following:
```
~$ docker load --input hello-world.tar.xz
exec: "xz": executable file not found in $PATH
```
.tar.gz works as expected.

I came across this issue 'accidentally' after forgetting I installed docker snap as part of an Ubuntu live server install. I then installed docker-ce as well and wondered why this (and only this very specific command) wasn't working.

**Comment by tianon** [comment]
Ah interesting, thanks for the report!  I guess we need to include `xz-utils` in our Snap (although I need to do a little testing to verify whether we need it in the engine, CLI, or both).
