### ISSUE TITLE
updating docker and docker-compose

### ISSUE THREAD

**Issue by Fuseteam** [docker-snap/docker-snap#37]
is there a plan to update docker and docker-compose to a more recent version?
docker seems to be at version 20.10.6 while docker-compose seems to be at 1.29.1 as opposed to docker version 19.03.15 and docker-compose version 1.25.5 in the snap

**Comment by Fuseteam** [comment]
as i  press the create issue button i noticed the pull requests :see_no_evil:

**Comment by tianon** [comment]
Build is in progress, 20.10.6 should be hitting edge shortly!

**Comment by Fuseteam** [comment]
awesome @tianon thanks!
do you have any thoughts on docker-compose 1.29.1?

**Comment by tianon** [comment]
Yeah, it's probably a good idea to update that as well, however I'm a bit more hesitant on that because I don't have any real testing of Compose here like I do Actions -- I believe Canonical has some spread tests (seen in this repository) that do some really basic testing of it, but I don't think those are going to be easy for us to run directly and would probably make sense to try and duplicate (at least the absolute basics) so we can bump without worrying as much about breaking some of the basic functionality (and then rely on the post-build testing that happens before we get all the way to the stable channel).

**Comment by Fuseteam** [comment]
ah i see uh so it comes down to testing if docker-compose works as expected hmmm

**Comment by augusto-herrmann** [comment]
I was looking for *anything* that would have a version of `docker-compose` that is [compatible with compose file version 3](https://docs.docker.com/compose/compose-file/compose-versioning/). For that, `docker-compose` version 1.27+ is required. All instructions I find on the internet, including [the official Docker documentation](https://docs.docker.com/compose/install/) tell us to user `curl` to install `docker-compose`. However, that is a bad practice as it never updates and does not keep track of security patches.

I tried to find anything (snap channels, or a ppa repository for apt) that would satisfy these requirements, but such a thing does not yet exist. Even the `latest/edge` channel of this snap has a very old `docker-compose` 1.25.5.

**Comment by Fuseteam** [comment]
hi @augusto-herrmann as mentioned earlier in this very thread the main blocker for the maintainer is a lack of means to ensure that docker-compose doesn't break whatsover under snap
if a rigous test could be run directly that would open the way

**Comment by augusto-herrmann** [comment]
Docker compose has tests [here](https://github.com/docker/compose/tree/master/tests).

To run them, just clone the [repository](https://github.com/docker/compose) and type

```bash
make test
```

so I don't understand what is really keeping `docker-compose` from being updated.

**Comment by Fuseteam** [comment]
> Docker compose has tests [here](https://github.com/docker/compose/tree/master/tests).
> 
> To run them, just clone the [repository](https://github.com/docker/compose) and type
> 
> ```shell
> make test
> ```
> 
> so I don't understand what is really keeping `docker-compose` from being updated.

Refer to https://github.com/docker-snap/docker-snap/issues/37#issuecomment-845558871
If you think it can be done 'easily' i'm sure a PR would be appreciated

**Comment by Fuseteam** [comment]
> @Fuseteam that comment is from May. I believe those tests have already been implemented, see [this file](https://github.com/docker-snap/docker-snap/blob/e179208f3a290fc6c69eca7c9431a714df2bf14b/spread/main/compose_file/task.yaml).

@augusto-herrmann whether it is from may or january is not important that was the current situation at the time i wrote that, you now have an new answer from tianon confirming the situation. again if it's "easy" and you consider it worth the effort i'm sure a PR is appreciated.

**Comment by tianon** [comment]
There's a PR up now at https://github.com/docker-snap/docker-snap/pull/48, and the CI generated a build at https://github.com/docker-snap/docker-snap/suites/3696078821/artifacts/93212286 -- it would help for someone to download/install that and do some basic testing to validate that at least some basic level of functionality is working as expected (`up`, `down`, `ps`, etc, then comment on https://github.com/docker-snap/docker-snap/pull/48 with the results).
