### ISSUE TITLE
installing docker cli plug-ins

### ISSUE THREAD

**Issue by Fuseteam** [docker-snap/docker-snap#38]
i am trying to install https://github.com/docker/app but i cannot seem to get it work as described in their readme
where should i place the plugin for the snap to recognize it?

i'm also open to alternatives that allow packaging and sharing compose files

**Comment by Fuseteam** [comment]
oh i found thanks to #12 i just have to put it in ~/snap/docker/current seems to work fine!
now i wonder what will happen when docker updates hmmmm

**Comment by kinghat** [comment]
the docker snap comes with `docker-compose` but i was trying to get the `docker compose`(v2) plugin working with the snap and am failing. i used the install directions for linux [here](https://docs.docker.com/compose/install/#install-compose-on-linux-systems) and also tried putting the executable in these locations as well:
> /home/kinghat/.docker/cli-plugins:
-rwxrwxr-x 1 kinghat kinghat  26M Apr 30 17:30 docker-compose

> /home/kinghat/snap/docker/1767:
-rwxrwxr-x 1 kinghat kinghat  26M Apr 30 17:37 docker-compose
/home/kinghat/snap/docker/1767/cli-plugins:
-rwxrwxr-x 1 kinghat kinghat  26M Apr 30 17:32 docker-compose

apparently `~/snap/docker/current` is a symlink:
> $ ll snap/docker/
total 20
drwxr-xr-x 5 kinghat kinghat 4096 Apr 30 17:14 ./
drwx------ 6 kinghat kinghat 4096 Apr 30 18:05 ../
drwxr-xr-x 2 kinghat kinghat 4096 Mar 24 19:12 1690/
drwxr-xr-x 3 kinghat kinghat 4096 Apr 30 17:37 1767/
drwxr-xr-x 2 kinghat kinghat 4096 Mar 24 19:12 common/
lrwxrwxrwx 1 kinghat kinghat    4 Apr 30 17:14 current -> 1767/

what am i missing?

also could compose v2 be considered to be included into the snap by default?

**Comment by tianon** [comment]
As of #70, `docker compose` is now built-in. :+1:

I've also just opened #71 to do the same with `docker buildx`.

**Comment by tianon** [comment]
With #70 and #71, I'm going to consider this mostly solved (since I think `buildx` and `compose` are the two most-desired of the actively supported CLI plugins), but I'll leave this discussion pinned for users who want to try other CLI plugins (which aren't officially supported).

**Comment by lunfardo** [comment]
Docker compose is not prebuilt at least on ubuntu-server version

**Comment by tianon** [comment]
If you got your `docker` from `snap install docker`, then you should have `docker compose` :confused:

**Comment by kevinbayes** [comment]
Nice,as of today I noticed you need to install the edge distribution for the right version.

**Comment by kinghat** [comment]
> Nice,as of today I noticed you need to install the edge distribution for the right version.

https://github.com/docker-snap/docker-snap/discussions/75
