### ISSUE TITLE
Please add raw-usb plug

### ISSUE THREAD

**Issue by bash-public-willpower** [docker-snap/docker-snap#56]
I need to connect a Conbee II USB-Stick to my docker container.
Host is ubuntu core. 

When I run 
`sudo snap connect docker:raw-usb :raw-usb`
I get
`error: snap "docker" has no plug named "raw-usb"`

Please add a raw-usb plug so that people can use raw usb inside docker.

**Comment by tianon** [comment]
Ah, interesting!  I've created https://github.com/docker-snap/docker-snap/pull/57 which *should* enable this -- once that CI finishes, there should be a build available from the CI artifacts which you could test to verify it actually works and fixes your use case before we merge. :+1:

**Comment by anonymouse64** [comment]
@bash-public-willpower can explain how you are trying to attach the USB stick to your container? AFAICT, docker should do this by adding the USB device to the container's device cgroup and/or mounting some things, both of which should be allowed by the docker-support interface already. Additionally, interfaces added to the docker snap do not automatically provide access to the things from the interface to _containers_. They are provided to _dockerd_ itself. So the only situation I would think this is necessary is if dockerd needs to inspect the USB device or do something more complicated than just adding another device to the device cgroup (which dockerd might very well do, I don't actually know). 

Also if you can attach the output of running `journalctl --no-pager | grep DENIED` on your host system running the docker snap that would be great to see if indeed dockerd is trying to poke something USB specific to setup the container.

**Comment by bash-public-willpower** [comment]
@anonymouse64 
@tianon 

I can conform that the error was on my side.
I used a wrong docker-compose command following this [guide](https://github.com/deconz-community/deconz-docker)

Instead of 
`devices:
      - /dev/ttyACM0:/dev/ttyACM0` 
  I used 
      `devices:
          - /dev/ttyACM0`

This lead to the following error in the container log:

`18:42:54:507 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)`

Then I wrongly assumed, that I hat to add my user to the dialout group which I could not accomplish in ubuntu **core**.

After using the right docker-compose commands I can confirm it is working now. Sorry for the confusion.

```

journalctl --no-pager | grep DENIED

Jan 04 14:14:35 rpi4-8gb-a audit[51169]: AVC apparmor="DENIED" operation="open" profile="snap.docker.compose" name="/proc/51169/mounts" pid=51169 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

Jan 04 14:14:35 rpi4-8gb-a kernel: audit: type=1400 audit(1641305675.093:29): apparmor="DENIED" operation="open" profile="snap.docker.compose" name="/proc/51169/mounts" pid=51169 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```
