### ISSUE TITLE
how to install older version eg. 19.03.x

### ISSUE THREAD

**Issue by vonProteus** [docker-snap/docker-snap#62]
i'm new to snaps and maybe my request is unfounded 
but can you add snap channel for older version? 
i need 19.03
now (2022-02-24) are available only:
```
channels:
  latest/stable:    20.10.11     2022-01-31 (1458) 122MB -
  latest/candidate: 20.10.11     2021-12-10 (1458) 122MB -
  latest/beta:      20.10.12     2022-02-23 (1690) 122MB -
  latest/edge:      20.10.12     2022-02-23 (1690) 122MB -
  17.03/stable:     17.03.2-ce-1 2017-07-20  (159)  42MB -
  17.03/candidate:  17.03.2-ce-1 2017-06-30  (159)  42MB -
  17.03/beta:       ↑
  17.03/edge:       17.03.2-ce-1 2017-06-30  (159)  42MB -
```

or alternatively how to install older version (eg. 19.03.15)

**Comment by tianon** [comment]
Unfortunately, Docker 19.03 is no longer supported (by the `docker` snap, Docker Inc, or the Moby project) -- what I would suggest if you must have 19.03.x would be to use some of the published (non-snap) builds of it from Docker, Inc, or if you must have a snap, creating your own custom build from the last commit here which included 19.03.x (641a1c73594c480abfc5958848d530d86ccb2bf5; https://github.com/docker-snap/docker-snap/tree/641a1c73594c480abfc5958848d530d86ccb2bf5).
