### ISSUE TITLE
Upgrade snap base to core20

### ISSUE THREAD

**Issue by BenD10** [docker-snap/docker-snap#65]
Continuing the discussion from the closed issue #15.

It seems the main hesitation remaining is dropping support for `i386`, however:
- Linux kernel dropped support for this architecture [nearly 10 years ago ](https://www.phoronix.com/scan.php?page=news_item&px=MTI0OTg)
- There are only [8,439 images available for i386](https://hub.docker.com/search?type=image&architecture=386) compared to the [5,319,128 images for x64](https://hub.docker.com/search?type=image&architecture=amd64) which shows the lack of popularity for this platform
- The last Ubuntu OS to [support i386 was 16.04](https://releases.ubuntu.com/16.04/), which [lost standard support last year](https://ubuntu.com/about/release-cycle)
- Intel [discontinued this platform since 2007](https://web.archive.org/web/20061007151235/http://developer.intel.com/design/pcn/Processors/D0106013.pdf), so it's been 15 years since this was even manufactured.

There doesn't seem to be much compelling evidence to continue supporting this platform.

`core22` will be released at some point this year as well, but likely not a target for this snap for some time.

**Comment by tianon** [comment]
I'd also love to start collecting a list of compelling reasons _to_ update -- beyond just "less duplication of bases" what are the benefits, especially while `core18` is still actively supported?

**Comment by tianon** [comment]
On the i386 point, we have a full order of magnitude more (metrics reporting) i386 users than either of ppc64el or s390x (which are both double digits and i386 is triple).

**Comment by jocado** [comment]
Hi @tianon :wave: 

Regarding reasons to update the base, I have a use case would seem to require it.  I would like to add NVIDIA support.  Please see issue, conversation and initial PR here:
- https://github.com/docker-snap/docker-snap/issues/91
- https://github.com/docker-snap/docker-snap/pull/90

I had a go at switching to the core22 base.  The actual snapcraft changes changes required seem fairly minimal.  Please see this diff for the specifics:
- https://github.com/jocado/docker-snap/compare/nvidia-support...jocado:docker-snap:core22-nvidia-support

What do you think ?

**Comment by tianon** [comment]
I'm going to cross my fingers and hope @xnox and/or @zhsj have some opinions/thoughts they're willing to share (probably a lot of overlap with what xnox has already put into the other threads but maybe slightly more specific about switching the base here with some of my concerns above and perhaps better ideas about how to address them or better context about whether they even matter). :bow: :+1:

**Comment by xnox** [comment]
i feel like creating a track for the current version of the snap, and leave it frozen at current revisions, and effectively remain as is, with base:core18 and all the legacy tooling in place.

The latest track should move on with times, and upgrade to core22 base, drop i386, gain riscv64, and move on with times.

This will include dropping upstream obsolete tooling.

In terms of users, the fast majority are on amd64 and the are roughly split between core20 and core22 users anyway based on other system atributes visible in the store. The snap users on Ubuntu Core 16 and 18 are a minority.

W.r.t. testing multi-arch support, testing arm64 things is trivial for most people (i have arm64 ubuntu thinkpad laptop, whilst general public can access free arm64 instances in oracle cloud, or use arm64 instances in azure /  gcp / aws as well). i386 is legacy, arm64 & riscv64 are the future.

And yes, I do not wish to introduce CUDA support on core18 based snaps, like at all.

This will be painful, thus I will need to further consult with people about this.

**Comment by xnox** [comment]
request for a legacy core18 track https://forum.snapcraft.io/t/new-legacy-track-for-docker-snap-core18/34266

**Comment by xnox** [comment]
core18 track has current releases out, so we can start to merge upgrades to core22 base, and enabling new things.

**Comment by jocado** [comment]
Great!  This is just to switch bases to start with.

https://github.com/docker-snap/docker-snap/pull/93
