### ISSUE TITLE
incude docker compose v2 in the snap

### ISSUE THREAD

**Issue by kinghat** [docker-snap/docker-snap#69]
im having trouble pairing the plugin with the snap manually but i think it would be better if it was included by default like `docker-compose` v1 currently is. i dont think there would be any namespace issues here either.

**Comment by tianon** [comment]
Totally agree -- I think it largely makes sense to bundle all the plugins that Docker Desktop does.  I also don't know for certain, but I don't think compose v1 has very much life left in it (now that v2 is GA).

**Comment by kinghat** [comment]
> Totally agree -- I think it largely makes sense to bundle all the plugins that Docker Desktop does. I also don't know for certain, but I don't think compose v1 has very much life left in it (now that v2 is GA).

were you able to get v2 working with the snap package?

**Comment by tianon** [comment]
Yeah, I've opened #70 which will add it -- once the CI finishes there, it'll have a `docker.snap` file you can download and test with (`snap install --dangerous ./docker.snap`) if you want to. :+1:
