### ISSUE TITLE
snap is broken on groovy due to apparmor 3 compatibility broken

### ISSUE THREAD

**Issue by anonymouse64** [docker-snap/docker-snap#8]
The docker snap is currently broken on Groovy due to : https://bugs.launchpad.net/snapd/+bug/1898038

We could either wait for upstream snapd to fix the bug, or we could update the docker snap to use `base: core20` in which case the apparmor_parser the docker snap uses will be from focal, which does not completely fail when presented with /etc from a 20.10 host like the current apparmor_parser from xenial does.

**Comment by anonymouse64** [comment]
> or we could update the docker snap to use base: core20 in which case the apparmor_parser the docker snap uses will be from focal, which does not completely fail

it seems after talking on IRC that this is not a good workaround for now, so we should just wait for upstream snapd to be fixed instead. 

There also would be the potentially significant amount of snapcraft'ing involved in porting the snapcraft.yaml to use `base: core20` instead of our current implicit `core` base.

**Comment by tianon** [comment]
Yeah, porting the Snap to `base: core20` has been on my TODO list for a while to at least consider and look into deeper, but setting up a development environment for building `base: core20` snaps is _way_ more complicated than `base: core`, so it's something that's hard for me to be motivated to spend a lot of time on.

**Comment by anonymouse64** [comment]
Porting to core20 also brings with it the complicated question of supporting i386 - do we drop it or do we maintain an i386 only version of the snap based on core16/core18? See https://forum.snapcraft.io/t/how-to-best-handle-i386-when-moving-a-snap-to-base-core20/17680 for more discussion

**Comment by diddledan** [comment]
a fix was merged upstream in moby/moby#41518

**Comment by tianon** [comment]
That fixes the parsing of the newer version numbers, but I believe this issue is due to/reporting an incompatibility between the version of `apparmor_parser` in our snap vs the version of apparmor on the host, right? (Slightly different problem)

**Comment by anonymouse64** [comment]
This was fixed in snapd with https://github.com/snapcore/snapd/pull/9516, which is available in snapd 2.47, so the docker snap could be updated to have `assumes: [snapd2.47]` to ensure that if a user is trying to install the docker snap on Groovy they will need to have at least snapd 2.47, but that is probably unnecessary given that snapd re-exec's on Groovy and snaps auto-updates itself.

I think this can be closed, I will leave it up to @tianon if adding `snapd2.47` to assumes is justified or not.
